/* Generated by db_schema.generate.js from db_schema.data.js */;

CREATE DATABASE data-delivery-roadmap;

USE data-delivery-roadmap;

CREATE TABLE op_theme (
  op_theme_id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  CONSTRAINT pk_op_theme_id PRIMARY KEY (op_theme_id)
);

CREATE TABLE op_program (
  op_program_id INT NOT NULL AUTO_INCREMENT,
  op_theme_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  short_name VARCHAR(25) NOT NULL,
  description VARCHAR(200) NOT NULL,
  CONSTRAINT pk_op_program_id PRIMARY KEY (op_program_id),
  CONSTRAINT fk_op_theme_id FOREIGN KEY (op_theme_id) REFERENCES op_theme(op_theme_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE device (
  device_id INT NOT NULL AUTO_INCREMENT,
  codename VARCHAR(100) NOT NULL,
  CONSTRAINT pk_device_id PRIMARY KEY (device_id)
);

CREATE TABLE data_program (
  data_program_id INT NOT NULL AUTO_INCREMENT,
  op_program_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  short_name VARCHAR(25) NOT NULL,
  description VARCHAR(200) NOT NULL,
  CONSTRAINT pk_data_program_id PRIMARY KEY (data_program_id),
  CONSTRAINT fk_op_program_id FOREIGN KEY (op_program_id) REFERENCES op_program(op_program_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE data_program__device (
  data_program_id INT NOT NULL,
  device_id INT NOT NULL,
  CONSTRAINT fk_data_program_id FOREIGN KEY (data_program_id) REFERENCES data_program(data_program_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_device_id FOREIGN KEY (device_id) REFERENCES device(device_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE data_track (
  data_track_id INT NOT NULL AUTO_INCREMENT,
  data_program_id INT NOT NULL,
  ml_purpose ENUM('POC','train+test','eval'),
  device_phase ENUM(''),
  data_bundle_types SET('ding','sirena','dump','discarded_event','ding+discard'),
  start_date DATE NOT NULL DEFAULT '1970-01-01',
  due_date DATE NOT NULL DEFAULT '1970-01-01',
  status ENUM('planned','postponed','in progress','cancelled','done'),
  CONSTRAINT pk_data_track_id PRIMARY KEY (data_track_id),
  CONSTRAINT fk_data_program_id FOREIGN KEY (data_program_id) REFERENCES data_program(data_program_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE data_track__secondary_op_program (
  data_track_id INT NOT NULL,
  op_program_id INT NOT NULL,
  CONSTRAINT fk_data_track_id FOREIGN KEY (data_track_id) REFERENCES data_track(data_track_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_op_program_id FOREIGN KEY (op_program_id) REFERENCES op_program(op_program_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE bundle_type (
  bundle_type_id INT NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  CONSTRAINT pk_bundle_type_id PRIMARY KEY (bundle_type_id)
);

CREATE TABLE markup_type (
  markup_type_id VARCHAR(20) NOT NULL AUTO_INCREMENT,
  name VARCHAR(100) NOT NULL,
  CONSTRAINT pk_markup_type_id PRIMARY KEY (markup_type_id)
);

CREATE TABLE markup_type__bundle_type (
  markup_type_id VARCHAR(20) NOT NULL,
  bundle_type_id INT NOT NULL,
  is_compatible BOOLEAN DEFAULT FALSE,
  CONSTRAINT fk_markup_type_id FOREIGN KEY (markup_type_id) REFERENCES markup_type(markup_type_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_bundle_type_id FOREIGN KEY (bundle_type_id) REFERENCES bundle_type(bundle_type_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE team (
  team_id INT NOT NULL AUTO_INCREMENT,
  headcount INT,
  is_machine BOOLEAN DEFAULT FALSE,
  CONSTRAINT pk_team_id PRIMARY KEY (team_id)
);

CREATE TABLE team__markup_type (
  team_id INT NOT NULL,
  markup_type_id VARCHAR(20) NOT NULL,
  skills SET('annotator','validator','verificator'),
  CONSTRAINT fk_team_id FOREIGN KEY (team_id) REFERENCES team(team_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_markup_type_id FOREIGN KEY (markup_type_id) REFERENCES markup_type(markup_type_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE data_subtrack (
  data_subtrack_id INT NOT NULL AUTO_INCREMENT,
  data_track_id INT NOT NULL,
  name VARCHAR(100) NOT NULL,
  markup_type_id VARCHAR(20) NOT NULL,
  annotation_team_id INT NOT NULL,
  validation_team_id INT NOT NULL,
  verification_team_id INT NOT NULL,
  CONSTRAINT pk_data_subtrack_id PRIMARY KEY (data_subtrack_id),
  CONSTRAINT fk_data_track_id FOREIGN KEY (data_track_id) REFERENCES data_track(data_track_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_markup_type_id FOREIGN KEY (markup_type_id) REFERENCES markup_type(markup_type_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_annotation_team_id FOREIGN KEY (annotation_team_id) REFERENCES team(team_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_validation_team_id FOREIGN KEY (validation_team_id) REFERENCES team(team_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_verification_team_id FOREIGN KEY (verification_team_id) REFERENCES team(team_id) ON UPDATE CASCADE ON DELETE RESTRICT
);

CREATE TABLE annotation_productivity (
  team_id INT NOT NULL,
  markup_type_id VARCHAR(20) NOT NULL,
  role ENUM('annotator','validator','verificator'),
  annotation_productivity_bundles_per_hour_per_head DECIMAL(6,2),
  CONSTRAINT fk_team_id FOREIGN KEY (team_id) REFERENCES team(team_id) ON UPDATE CASCADE ON DELETE RESTRICT,
  CONSTRAINT fk_markup_type_id FOREIGN KEY (markup_type_id) REFERENCES markup_type(markup_type_id) ON UPDATE CASCADE ON DELETE RESTRICT
);
